---
- name: Update apt cache and install Docker Compose v2
  ansible.builtin.apt:
    name:
      - python3-pip
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: yes
