---
app_image: "nginx:latest"  # Replace with the actual image if needed
app_instances: 3
app_memory_limit: "1g"
app_cpu_limit: "0.3"
tuning: true
debug: false
external_url: "https://staging/approve"
client: "staging_client_external"
interaction_mode: "API"
device_id: 32443532
