all:
  children:
    dev:
      hosts:
        dev_host1:
          ansible_host: 3.77.202.137
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/my-ssh-key.pem
          ansible_python_interpreter: /usr/bin/python3
