all:
  children:
    staging:
      hosts:
        staging_host2:
          ansible_host: 18.185.238.15
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/my-ssh-key.pem
          ansible_python_interpreter: /usr/bin/python3
