all:
  children:
    staging:
      hosts:
        staging_host2:
          ansible_host: 3.71.78.70
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/my-ssh-key.pem
          ansible_python_interpreter: /usr/bin/python3
